name: Docker CI [multi-arch]

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.DEVFLOWS_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.DEVFLOWS_AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
            platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: public.ecr.aws/k1t8c0v2/kiam:v4.2
      - name: Log out of Amazon ECR
        if: always()
        run: docker logout public.ecr.aws
